server.port=8080

# ===== MySQL (XAMPP / MariaDB) =====
spring.datasource.url=jdbc:mysql://localhost:3306/demo_db?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# ===== i18n =====
spring.messages.basename=messages
spring.messages.encoding=UTF-8

# ===== JWT =====
# (mínimo 32 caracteres)
app.jwt.secret=MI_SECRETO_SUPER_LARGO_32_CHARS_MINIMO_123456
app.jwt.expiration-ms=86400000